context.modules = [
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Main (Virtual)"
            capture.props = {
                node.name = "sink-main"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
                stream.dont-remix = true
            }
        }
    }

    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Games (Virtual)"
            capture.props = {
                node.name = "sink-games"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
                stream.dont-remix = true
            }
        }
    }

    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Aux (Virtual)"
            capture.props = {
                node.name = "sink-aux"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
                stream.dont-remix = true
            }
        }
    }

    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Browser (Virtual)"
            capture.props = {
                node.name = "sink-browser"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
                stream.dont-remix = true
            }
        }
    }

    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Discord (Virtual)"
            capture.props = {
                node.name = "sink-discord"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
                stream.dont-remix = true
            }
        }
    }
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Spotify (Virtual)"
            capture.props = {
                node.name = "sink-spotify"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
                stream.dont-remix = true
            }
        }
    }
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Mic (Sink)"
            capture.props = {
                node.name = "sink-mic"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
                stream.dont-remix = true
            }
        }
    }
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Null (Sink)"
            capture.props = {
                node.name = "null-mic"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
                stream.dont-remix = true
            }
        }
    }
]
