context.modules = [
{
    name = libpipewire-module-vban-recv
    args = {
        sess.latency.msec = 5
        audio.format = "S16LE"
        audio.rate = 48000
        audio.channels = 2
        stream.rules = [

            {
                matches = [{ sess.name = "WIN_MIC" }]
                actions = {
                    create-stream = {
                        stream.props = {
                            node.name = "vban-win-mic"
                            node.description = "WIN_MIC"
                            audio.position = [ FL FR ]
                        }
                    }
                }
            }

            {
                matches = [{ sess.name = "WIN_GAMES" }]
                actions = {
                    create-stream = {
                        stream.props = {
                            node.name = "vban-win-games"
                            node.description = "WIN_GAMES"
                            audio.position = [ FL FR ]
                        }
                    }
                }
            }

            {
                matches = [{ sess.name = "WIN_AUX" }]
                actions = {
                    create-stream = {
                        stream.props = {
                            node.name = "vban-win-aux"
                            node.description = "WIN_AUX"
                            audio.position = [ FL FR ]
                        }
                    }
                }
            }

            {
                matches = [{ sess.name = "WIN_MAIN" }]
                actions = {
                    create-stream = {
                        stream.props = {
                            node.name = "vban-win-main"
                            node.description = "WIN_MAIN"
                            audio.position = [ FL FR ]
                        }
                    }
                }
            }

        ]
    }
}
]
