context.modules = [
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Mic (Virtual)"

            capture.props = {
                node.passive = true
                stream.dont-remix = true
            }

            playback.props = {
                node.name = "mic-virtual"
                node.description = "Mic (Virtual)"
                media.class = "Audio/Source"
                audio.position = [ FL FR ]
                stream.dont-remix = true
            }
        }
    }
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Main (Loopback)"

            capture.props = {
                node.passive = true
                stream.dont-remix = true
            }

            playback.props = {
                node.name = "main-loopback"
                node.description = "Main (Loopback)"
                media.class = "Audio/Source"
                audio.position = [ FL FR ]
                stream.dont-remix = true
            }
        }
    }
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Aux (Loopback)"

            capture.props = {
                node.passive = true
                stream.dont-remix = true
            }

            playback.props = {
                node.name = "aux-loopback"
                node.description = "Aux (Loopback)"
                media.class = "Audio/Source"
                audio.position = [ FL FR ]
                stream.dont-remix = true
            }
        }
    }
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Games (Loopback)"

            capture.props = {
                node.passive = true
                stream.dont-remix = true
            }

            playback.props = {
                node.name = "games-loopback"
                node.description = "games (Loopback)"
                media.class = "Audio/Source"
                audio.position = [ FL FR ]
                stream.dont-remix = true
            }
        }
    }
]
