# ==========================================================
# Shadows
# ==========================================================

shadow = true;
shadow-radius = 3;
shadow-offset-x = -3;
shadow-offset-y = 3;
shadow-opacity = 0.9;

shadow-exclude = [
    "class_g = 'Polybar'",
    "class_g = 'Rofi'"
];


# ==========================================================
# General
# ==========================================================

vsync = true;


# ==========================================================
# Blur
# ==========================================================

blur-method = "dual_kawase";
blur-strength = 6;

blur-background = true;
blur-background-frame = true;


# ==========================================================
# Opacity
# ==========================================================

inactive-opacity = 1.0;


# ==========================================================
# Fading
# ==========================================================

fading = true;

fade-in-step = 0.035;
fade-out-step = 0.035;
fade-delta = 6;

no-fading-openclose = true;


# ==========================================================
# Animations
# ==========================================================

animations = (
    {
        triggers = [
            "open",
            "show"
        ];

        scale-x = {
            curve = "cubic-bezier(0.2, 1.4, 0.35, 1)";
            duration = 0.32;
            start = 0.82;
            end = 1;
        };

        scale-y = "scale-x";

        offset-x = "(1 - scale-x) * window-width / 2";
        offset-y = "(1 - scale-y) * window-height / 2";

        shadow-scale-x = "scale-x";
        shadow-scale-y = "scale-y";

        shadow-offset-x = "offset-x";
        shadow-offset-y = "offset-y";

        opacity = {
            duration = 0.18;
            start = 0;
            end = 1;
        };
    },

    {
        triggers = [
            "close",
            "hide"
        ];

        preset = "disappear";
        scale = 0.85;
        duration = 0.18;
    }
);
