#!/usr/bin/env bash

export XDG_CURRENT_DESKTOP="bspwm"

setxkbmap -layout us -variant intl 

set -a
eval "$(/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator)"
set +a

dbus-update-activation-environment --systemd --all

MODULES_DIR="$HOME/.config/bspwm/atno"

if ! pgrep -x xssproxy >/dev/null; then
    xssproxy &
fi

. "$MODULES_DIR/initial.sh"
. "$MODULES_DIR/monitors.sh"
. "$MODULES_DIR/appearance.sh"
. "$MODULES_DIR/windowrules.sh"
. "$MODULES_DIR/autostart.sh"
. "$MODULES_DIR/clipboard.sh"



