#!/usr/bin/env bash

export XDG_CURRENT_DESKTOP="bspwm"

setxkbmap -layout us -variant intl

SYSTEMD_ENV_GENERATOR="/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator"

if [[ -x "$SYSTEMD_ENV_GENERATOR" ]]; then
    set -a
    eval "$("$SYSTEMD_ENV_GENERATOR")"
    set +a
fi

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment --systemd --all
fi

MODULES_DIR="$HOME/.config/bspwm/atno"

. "$MODULES_DIR/initial.sh"
. "$MODULES_DIR/monitors.sh"
. "$MODULES_DIR/appearance.sh"
. "$MODULES_DIR/windowrules.sh"
. "$MODULES_DIR/autostart.sh"
. "$MODULES_DIR/clipboard.sh"
